language: java
install: true
script:
  - mvn install
sudo: required
services:
  - docker
after_success:
  - docker build -t se_methods .
  - docker run se_methods
  - docker network create --driver bridge se-methods
  - docker pull mongo
  - docker run --network se-methods se_methods
